controller_manager:
  ros__parameters:
    update_rate: 50

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_link
